import './globals.css'
import { Inter, Silkscreen, Edu_SA_Beginner } from 'next/font/google'

export const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})
 
export const slikScreen = Silkscreen({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
})

export const eduSABegginer = Edu_SA_Beginner({
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
